=== Planteome/termgenie/TermGenie/TermGenieCore/src/main/resources/ontology-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="ontologyconfiguration" type="ontologyconfigurationType" />
  <xsd:complexType name="ontologyconfigurationType">
    <xsd:sequence>
      <xsd:element name="ontology" type="ontologyType" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="ontologyType">
    <xsd:sequence>
      <xsd:element name="source" type="xsd:string" maxOccurs="1" minOccurs="1"/>
      <xsd:element name="supports" type="supportsType" maxOccurs="1" minOccurs="0"/>
      <xsd:element name="roots" type="rootsType" maxOccurs="1" minOccurs="1"/>
      <xsd:element name="requires" type="requiresType" maxOccurs="1" minOccurs="0"/>
      <xsd:element name="ontologybranch" type="ontologybranchType" maxOccurs="unbounded" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="longName" type="xsd:string" use="optional" />
  </xsd:complexType>
  <xsd:complexType name="ontologybranchType">
    <xsd:sequence>
      <xsd:element name="roots" type="rootsType" maxOccurs="1" minOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="rootsType">
    <xsd:sequence>
      <xsd:element name="root" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="requiresType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="supportsType">
    <xsd:sequence>
      <xsd:element name="support" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppHPO/src/main/resources/ontology-configuration_hpo.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="HumanPhenotype">
		<source>http://compbio.charite.de/svn/hpo/trunk/src/ontology/human-phenotype-ontology.obo</source>
		<supports>
			<support>http://compbio.charite.de/svn/hpo/trunk/src/ontology/human-phenotype-ontology_xp.obo</support>
		</supports>
		<roots>
			<root>HP:0000001</root>
		</roots>
	</ontology>
	<ontology name="FMA" longName="Foundational Model of Anatomy ontology">
		<source>http://obo.svn.sourceforge.net/viewvc/*checkout*/obo/fma-conversion/trunk/fma2_obo.obo</source>
		<roots>
			<root>FMA:62955</root>
		</roots>
	</ontology>
	<ontology name="PATO" longName="Phenotypic Quality Ontology">
		<source>http://pato.googlecode.com/svn/trunk/quality.obo</source>
		<roots>
			<root>PATO:0000001</root>
		</roots>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppAll/src/main/resources/ontology-configuration_all.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://www.geneontology.org/ontology/obo_format_1_2/gene_ontology_ext.obo
		</source>
		<supports>
			<support>http://www.geneontology.org/scratch/xps/biological_process_xp_self.obo</support>
			<support>http://www.geneontology.org/scratch/xps/biological_process_xp_cellular_component.obo</support>
			<support>http://www.geneontology.org/scratch/xps/molecular_function_xp_protein.obo</support>
			<support>http://www.geneontology.org/scratch/xps/biological_process_xp_uber_anatomy.obo</support>
			<!-- <support>http://www.geneontology.org/scratch/xps/biological_process_xp_plant_anatomy.obo</support> -->
			<support>http://www.geneontology.org/scratch/xps/cellular_component_xp_protein.obo</support>
		</supports>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
		<requires>
			<name>ProteinOntology</name>
			<name>Uberon</name>
			<name>PO</name> <!-- Plant ontology -->
		</requires>
		<ontologybranch name="biological_process">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="molecular_function">
			<roots>
				<root>GO:0003674</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="cellular_component">
			<roots>
				<root>GO:0005575</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="macromolecular_complex">
			<roots>
				<root>GO:0032991</root>
			</roots>
		</ontologybranch>
	</ontology>
	<ontology name="ProteinOntology">
		<source>ftp://ftp.pir.georgetown.edu/databases/ontology/pro_obo/pro.obo</source>
		<roots>
			<root>PR:000000001</root>
		</roots>
	</ontology>
	<ontology name="Uberon">
		<source>http://github.com/cmungall/uberon/raw/master/uberon.obo</source>
		<roots>
			<root>UBERON:0001062</root>
		</roots>
	</ontology>
	<ontology name="HumanPhenotype">
		<source>http://compbio.charite.de/svn/hpo/trunk/src/ontology/human-phenotype-ontology.obo</source>
		<supports>
			<support>http://compbio.charite.de/svn/hpo/trunk/src/ontology/human-phenotype-ontology_xp.obo</support>
		</supports>
		<roots>
			<root>HP:0000001</root>
		</roots>
	</ontology>
	<ontology name="FMA" longName="Foundational Model of Anatomy ontology">
		<source>http://obo.svn.sourceforge.net/viewvc/*checkout*/obo/fma-conversion/trunk/fma2_obo.obo</source>
		<roots>
			<root>FMA:62955</root>
		</roots>
	</ontology>
	<ontology name="PATO" longName="Phenotypic Quality Ontology">
		<source>http://pato.googlecode.com/svn/trunk/quality.obo</source>
		<roots>
			<root>PATO:0000001</root>
		</roots>
	</ontology>
	<ontology name="OMP" longName="Mammalian Phenotype Ontology">
		<source>http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/phenotype/mammalian_phenotype.obo</source>
		<roots>
			<root>MP:0000001</root>
		</roots>
	</ontology>
	<ontology name="CL" longName="Cell (Type) Ontology">
		<source>http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/anatomy/cell_type/cell.obo</source>
		<roots>
			<root>CL:0000000</root>
		</roots>
	</ontology>
	<ontology name="PO" longName="Plant ontology">
		<source>http://palea.cgrb.oregonstate.edu/viewsvn/Poc/tags/live/plant_ontology.obo?view=co</source>
		<roots>
			<root>PO:0025131</root>
			<root>PO:0009012</root>
		</roots>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieJQuery/src/test/resources/ontology-configuration_simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://www.geneontology.org/ontology/editors/gene_ontology_write.obo
		</source>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
		<ontologybranch name="biological_process">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppEnvo/src/main/resources/ontology-configuration_envo.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="ENVO" longName="Environment Ontology">
		<source>http://purl.obolibrary.org/obo/envo.owl</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/uberon.owl</support>
			<support>http://purl.obolibrary.org/obo/po.owl</support>
		</supports>
		<roots>
			<root>ENVO:00000000</root>		<!-- geographic feature -->
			<root>PO:0025131</root>		<!-- plant anatomical entity -->
			<root>UBERON:0001062</root> <!-- anatomical entity -->
		</roots>
		<ontologybranch name="entities">
			<roots>
				<root>PO:0025131</root> <!-- plant anatomical entity -->
				<root>UBERON:0001062</root> <!-- anatomical entity -->
			</roots>
		</ontologybranch>
		<ontologybranch name="default_envo">
			<roots>
				<root>ENVO:00000000</root> <!-- geographic feature -->
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/TermGenieCore/src/test/resources/ontology-configuration_import-test-case.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://test.purl.obolibrary.org/obo/base.obo</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/go/extensions/bio-chebi.owl</support>
		</supports>
		<roots>
			<root>FOO:0001</root>
			<root>CHEBI:24309</root>
		</roots>
		<ontologybranch name="foo">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="chebi">
			<roots>
				<root>CHEBI:24309</root>
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppBatto/src/main/resources/ontology-configuration_batto.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="OBA">
		<source>http://purl.obolibrary.org/obo/go/extensions/bio-attributes.obo</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/go/extensions/x-attribute.obo</support>
		</supports>
		<roots>
			<root>OBA:0000001</root>
			<root>UBERON:0001062</root> <!-- anatomical entity -->
			<root>CL:0000003</root> <!-- native cell -->
			<root>GO:0005575</root> <!-- cellular component -->
			<root>PATO:0000001</root> <!-- quality -->
			<root>PO:0025131</root> <!-- plant anatomical entity -->
		</roots>
		<ontologybranch name="entity">
			<!-- Entity: any term from uberon, CL or GO-CC -->
			<roots>
				<root>UBERON:0001062</root> <!-- anatomical entity -->
				<root>CL:0000003</root> <!-- native cell -->
				<root>GO:0005575</root> <!-- cellular component -->
				<root>PO:0025131</root> <!-- plant anatomical entity -->
			</roots>
		</ontologybranch>
		<ontologybranch name="quality">
			<roots>
				<root>PATO:0000001</root> <!-- quality -->
			</roots>
		</ontologybranch>
		<ontologybranch name="default_oba">
			<roots>
				<root>OBA:0000001</root>
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/TermGenieRulesDynamic/src/test/resources/ontology-configuration_anatomy.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://www.geneontology.org/ontology/editors/gene_ontology_write.obo
		</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/go/extensions/x-metazoan-anatomy-importer.owl</support>
		</supports>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
		<ontologybranch name="biological_process">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="molecular_function">
			<roots>
				<root>GO:0003674</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="cellular_component">
			<roots>
				<root>GO:0005575</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="UberonDevelopment">
			<roots>
				<root>UBERON:0001062</root> <!-- chemical entity -->
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppMP/src/main/resources/ontology-configuration_mp.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="MP" longName="Phenotype Ontology">
		<source>http://purl.obolibrary.org/obo/mp.owl</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/go.owl</support>
			<support>http://purl.obolibrary.org/obo/uberon.owl</support>
			<support>http://purl.obolibrary.org/obo/cl.owl</support>
			<support>http://purl.obolibrary.org/obo/pato.owl</support>
			<!-- <support>http://purl.obolibrary.org/obo/chebi.owl</support> -->
		</supports>
		<roots>
			<root>MP:0000001</root>		<!-- mammalian phenotype -->
			<root>GO:0003674</root>		<!-- molecular_function -->
			<root>GO:0008150</root> 	<!-- biological_process -->
			<root>GO:0005575</root>		<!-- cellular_component -->
			<root>CL:0000003</root> 	<!-- native cell -->
			<root>UBERON:0001062</root> <!-- anatomical entity -->
			<root>PATO:0000001</root>	<!-- quality -->
			<root>CHEBI:24431</root>	<!-- chemical entity -->
		</roots>
		<ontologybranch name="entities">
			<roots>
				<root>GO:0005575</root> <!-- cellular_component -->
				<root>CL:0000003</root> <!-- native cell -->
				<root>UBERON:0001062</root> <!-- anatomical entity -->
			</roots>
		</ontologybranch>
		<ontologybranch name="occurent">
			<roots>
				<root>GO:0003674</root> <!-- molecular_function -->
				<root>GO:0008150</root> <!-- biological_process -->
			</roots>
		</ontologybranch>
		<ontologybranch name="onset_quality">
			<roots>
				<root>PATO:0002325</root> <!-- onset quality -->
			</roots>
		</ontologybranch>
		<ontologybranch name="default_mp">
			<roots>
				<root>MP:0000001</root> <!-- mammalian phenotype -->
			</roots>
		</ontologybranch>
		<ontologybranch name="chemicals">
			<roots>
				<root>CHEBI:24431</root> <!-- chemical entity -->
			</roots>
		</ontologybranch>
		<ontologybranch name="uberon_location">
			<roots>
				<root>UBERON:0001062</root> <!-- anatomical entity -->
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>
