=== Planteome/termgenie/TermGenie/TermGenieCore/src/main/resources/ontology-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="ontologyconfiguration" type="ontologyconfigurationType" />
  <xsd:complexType name="ontologyconfigurationType">
    <xsd:sequence>
      <xsd:element name="ontology" type="ontologyType" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="ontologyType">
    <xsd:sequence>
      <xsd:element name="source" type="xsd:string" maxOccurs="1" minOccurs="1"/>
      <xsd:element name="supports" type="supportsType" maxOccurs="1" minOccurs="0"/>
      <xsd:element name="roots" type="rootsType" maxOccurs="1" minOccurs="1"/>
      <xsd:element name="requires" type="requiresType" maxOccurs="1" minOccurs="0"/>
      <xsd:element name="ontologybranch" type="ontologybranchType" maxOccurs="unbounded" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="longName" type="xsd:string" use="optional" />
  </xsd:complexType>
  <xsd:complexType name="ontologybranchType">
    <xsd:sequence>
      <xsd:element name="roots" type="rootsType" maxOccurs="1" minOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="rootsType">
    <xsd:sequence>
      <xsd:element name="root" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="requiresType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="supportsType">
    <xsd:sequence>
      <xsd:element name="support" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== Planteome/termgenie/TermGenie/TermGenieRulesDynamic/src/test/resources/ontology-configuration_chemical.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://purl.obolibrary.org/obo/go.owl</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/go/extensions/x-chemical-importer.owl</support>
		</supports>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
		<ontologybranch name="biological_process">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="molecular_function">
			<roots>
				<root>GO:0003674</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="cellular_component">
			<roots>
				<root>GO:0005575</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="ChemicalImporter">
			<roots>
				<root>CHEBI:24431</root> <!-- chemical entity -->
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppGO/src/main/resources/go-ontology-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://www.geneontology.org/ontology/obo_format_1_2/gene_ontology_ext.obo
		</source>
		<supports>
			<!-- <support>http://www.geneontology.org/scratch/xps/biological_process_xp_self.obo</support> -->
			<!-- <support>http://www.geneontology.org/scratch/xps/biological_process_xp_cellular_component.obo</support> -->
			<support>http://www.geneontology.org/scratch/xps/molecular_function_xp_protein.obo
			</support>
			<!-- <support>http://www.geneontology.org/scratch/xps/biological_process_xp_uber_anatomy.obo</support> -->
			<support>http://www.geneontology.org/scratch/xps/biological_process_xp_plant_anatomy.obo
			</support>
			<support>http://www.geneontology.org/scratch/xps/cellular_component_xp_protein.obo
			</support>
		</supports>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
		<requires>
			<name>ProteinOntology</name>
			<name>Uberon</name>
			<name>PO</name> <!-- Plant ontology -->
		</requires>
		<ontologybranch name="biological_process">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="molecular_function">
			<roots>
				<root>GO:0003674</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="cellular_component">
			<roots>
				<root>GO:0005575</root>
			</roots>
		</ontologybranch>
	</ontology>
	<ontology name="ProteinOntology">
		<source>ftp://ftp.pir.georgetown.edu/databases/ontology/pro_obo/pro.obo</source>
		<roots>
			<root>PR:000000001</root>
		</roots>
	</ontology>
	<ontology name="Uberon">
		<source>http://github.com/cmungall/uberon/raw/master/uberon.obo</source>
		<roots>
			<root>UBERON:0001062</root>
		</roots>
	</ontology>
	<ontology name="PO" longName="Plant ontology">
		<source>http://palea.cgrb.oregonstate.edu/viewsvn/Poc/tags/live/plant_ontology.obo?view=co</source>
		<roots>
			<root>PO:0025131</root>
			<root>PO:0009012</root>
		</roots>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/TermGenieRulesDynamic/src/test/resources/ontology-configuration_regulation_by.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://www.geneontology.org/ontology/obo_format_1_2/gene_ontology_ext.obo</source>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
		<ontologybranch name="biological_process">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="regulation of biological process">
			<roots>
				<root>GO:0050789</root>
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppHP/src/test/resources/ontology-configuration_hp_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="HP" longName="Human Phenotype Ontology">
		<source>http://purl.obolibrary.org/obo/hp/hp-edit.owl</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/go.owl</support>
			<support>http://purl.obolibrary.org/obo/uberon.owl</support>
			<support>http://purl.obolibrary.org/obo/cl.owl</support>
			<support>http://purl.obolibrary.org/obo/pato.owl</support>
		</supports>
		<roots>
			<root>HP:0000001</root>		<!-- All human phenotypes -->
			<root>GO:0005575</root>		<!-- cellular_component -->
			<root>CL:0000003</root> 	<!-- native cell -->
			<root>UBERON:0001062</root> <!-- anatomical entity -->
		</roots>
		<ontologybranch name="entities">
			<roots>
				<root>GO:0005575</root> <!-- cellular_component -->
				<root>CL:0000003</root> <!-- native cell -->
				<root>UBERON:0001062</root> <!-- anatomical entity -->
			</roots>
		</ontologybranch>
		<ontologybranch name="anatomy">
			<roots>
				<root>UBERON:0001062</root> <!-- anatomical entity -->
			</roots>
		</ontologybranch>
		<ontologybranch name="default_hp">
			<roots>
				<root>HP:0000001</root> <!-- All human phenotypes -->
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppOMP/src/main/resources/ontology-configuration_omp.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://www.geneontology.org/ontology/obo_format_1_2/gene_ontology_ext.obo
		</source>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
	</ontology>
	<ontology name="PATO" longName="Phenotypic Quality Ontology">
		<source>http://pato.googlecode.com/svn/trunk/quality.obo</source>
		<roots>
			<root>PATO:0000001</root>
		</roots>
	</ontology>
	<ontology name="OMP" longName="Mammalian Phenotype Ontology">
		<source>http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/phenotype/mammalian_phenotype.obo</source>
		<roots>
			<root>MP:0000001</root>
		</roots>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/TermGenieRulesDynamic/src/test/resources/ontology-configuration_simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://purl.obolibrary.org/obo/go/extensions/go-plus.owl</source>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
		<ontologybranch name="biological_process">
			<roots>
				<root>GO:0008150</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="molecular_function">
			<roots>
				<root>GO:0003674</root>
			</roots>
		</ontologybranch>
		<ontologybranch name="cellular_component">
			<roots>
				<root>GO:0005575</root>
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/TermGenieRulesDynamic/src/test/resources/ontology-configuration_freeform.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="GeneOntology">
		<source>http://www.geneontology.org/ontology/editors/gene_ontology_write.obo</source>
		<supports>
			<support>http://www.geneontology.org/ontology/editors/gene_ontology_xp_write.obo</support>
			<support>http://purl.obolibrary.org/obo/go/extensions/x-disjoint.owl</support>
		</supports>
		<roots>
			<root>GO:0008150</root>
			<root>GO:0003674</root>
			<root>GO:0005575</root>
		</roots>
	</ontology>
</ontologyconfiguration>

=== Planteome/termgenie/TermGenie/WebApplications/TermGenieWebAppTO/src/main/resources/ontology-configuration_to.xml
<?xml version="1.0" encoding="UTF-8"?>
<ontologyconfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ontology-configuration.xsd">
	<ontology name="TO">
		<source>http://purl.obolibrary.org/obo/to.owl</source>
		<supports>
			<support>http://purl.obolibrary.org/obo/cl.owl</support>
			<support>http://purl.obolibrary.org/obo/go.owl</support>
			<support>http://purl.obolibrary.org/obo/pato.owl</support>
			<support>http://purl.obolibrary.org/obo/po.owl</support>
		</supports>
		<roots>
			<root>TO:0000387</root> <!-- plant trait -->
			<root>CL:0000003</root> <!-- native cell -->
			<root>GO:0005575</root> <!-- cellular component -->
			<root>PATO:0000001</root> <!-- quality -->
			<root>PO:0025131</root> <!-- plant anatomical entity -->
		</roots>
		<ontologybranch name="entity">
			<!-- Entity: any term from uberon, CL or GO-CC -->
			<roots>
				<root>CL:0000003</root> <!-- native cell -->
				<root>GO:0005575</root> <!-- cellular component -->
				<root>PO:0025131</root> <!-- plant anatomical entity -->
			</roots>
		</ontologybranch>
		<ontologybranch name="quality">
			<roots>
				<root>PATO:0000001</root> <!-- quality -->
			</roots>
		</ontologybranch>
		<ontologybranch name="default_to">
			<roots>
				<root>TO:0000387</root> <!-- plant trait -->
			</roots>
		</ontologybranch>
	</ontology>
</ontologyconfiguration>
