=== Planteome/termgenie/TermGenie/TermGenieRulesDynamic/src/main/resources/default_termgenie_rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" version="1.0"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="termgenietemplates" type="termgenietemplatesType" />
	<xsd:complexType name="termgenietemplatesType">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" name="template" type="templateType" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="templateType">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				maxOccurs="1" minOccurs="1" />
			<xsd:element name="hint" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="ontology" type="ontologyType"
				maxOccurs="1" minOccurs="1" />
			<xsd:element name="external" type="externalType"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="obonamespace" type="xsd:string"
				maxOccurs="1" minOccurs="1" />
			<xsd:element name="requires" type="xsd:string" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="fields" type="fieldsType" maxOccurs="1"
				minOccurs="1" />
			<xsd:element name="rule" type="xsd:string" maxOccurs="1"
				minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="displayname" type="xsd:string" use="optional" />
	</xsd:complexType>
	<xsd:complexType name="fieldsType">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" name="field" type="fieldType" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="fieldType">
		<xsd:sequence>
			<xsd:element name="ontology" type="ontologyType" maxOccurs="unbounded" minOccurs="0"/>
			<xsd:element name="cardinality" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
            <xsd:element name="prefixes" type="prefixesType" maxOccurs="1" minOccurs="0" />
        </xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="required" type="xsd:boolean" use="optional"/>
	</xsd:complexType>
  <xsd:complexType name="prefixesType">
    <xsd:sequence>
      <xsd:element maxOccurs="unbounded" name="prefix" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>
 <xsd:complexType name="ontologyType">
    <xsd:sequence>
      <xsd:element name="branch" type="xsd:string" maxOccurs="1" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

 <xsd:complexType name="externalType">
 	<xsd:sequence>
 		<xsd:element name="ontology" type="ontologyType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
 	</xsd:sequence>
 </xsd:complexType>
</xsd:schema>

=== Planteome/termgenie/TermGenie/TermGenieRulesDynamic/src/main/resources/default_termgenie_rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<termgenietemplates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="default_termgenie_rules.xsd">
	<template name="all_regulation" displayname="regulation: biological_process">
		<description>Select all three subtemplates to generate terms for
			regulation, negative regulations and positive regulation (for
			biological processes). Names, synonyms and definitions are all
			generated automatically</description>
		<ontology name="GeneOntology" />
		<obonamespace>biological_process</obonamespace>
		<fields>
			<field name="target" required="true">
				<prefixes>
					<prefix>regulation</prefix>
					<prefix>negative_regulation</prefix>
					<prefix>positive_regulation</prefix>
				</prefixes>
				<ontology name="GeneOntology">
					<branch>biological_process</branch>
				</ontology>
			</field>
			<field name="DefX_Ref">
				<cardinality>1..N</cardinality>
			</field>
		</fields>
		<rule> <![CDATA[
function run() {
  var go = GeneOntology;
  var x = termgenie.getSingleTerm("target", go);
  // biological_process
  var check = termgenie.checkGenus(x, "GO:0008150", go);
  if (check.isGenus() !== true) {
    termgenie.error(check.error());
    return;
  }
  if (termgenie.genus(x, "GO:0065007", go)) {
    // biological regulation
    termgenie.error(
      "Cannot create 'regulation of regulation of X' terms. The term "+
      termgenie.getTermShortInfo("GO:0065007", go)+
      " is a parent of "+
      termgenie.getTermShortInfo(x, go)+
      ".");
    return;
  }
  var prefixes = termgenie.getInputs("target");
  if (!prefixes || prefixes === null || prefixes.length === 0) {
    termgenie.error("Could not create a term for X, as no prefix was selected");
    return;
  }
  var count = 0;
  if (termgenie.contains(prefixes, "regulation")) {
    var label = "regulation of "+ termgenie.name(x, go);
    var definition = "Any process that modulates the frequency, rate or extent of "+termgenie.name(x, go)+".";
    var synonyms = termgenie.synonyms("regulation of ", x, go, null, label);
    var cdef = termgenie.cdef("GO:0065007");
    cdef.differentium("regulates", x, go);
    termgenie.createTerm(label, definition, synonyms, cdef);
    count += 1;
  }
  if (termgenie.contains(prefixes, "negative_regulation")) {
    var label = "negative regulation of "+ termgenie.name(x, go);
    var definition = "Any process that stops, prevents or reduces the frequency, rate or extent of "+termgenie.name(x, go)+".";
    var synonyms = termgenie.synonyms("negative regulation of ", x, go, null, label);
    var cdef = termgenie.cdef("GO:0065007");
    cdef.differentium("negatively_regulates", x, go);
    termgenie.createTerm(label, definition, synonyms, cdef);
    count += 1;
  }
  if (termgenie.contains(prefixes, "positive_regulation")) {
    var label = "positive regulation of "+ termgenie.name(x, go);
    var definition = "Any process that activates or increases the frequency, rate or extent of "+termgenie.name(x, go)+".";
    var synonyms = termgenie.synonyms("positive regulation of ", x, go, null, label);
    var cdef = termgenie.cdef("GO:0065007");
    cdef.differentium("positively_regulates", x, go);
    termgenie.createTerm(label, definition, synonyms, cdef);
    count += 1;
  }
  if (count === 0) {
    termgenie.error("Could not create a term for X, as no known prefix was selected");
  }
};]]>
		</rule>
	</template>
	<template name="all_regulation_mf" displayname="regulation: molecular_function">
		<description>Select all three subtemplates to generate terms for
			regulation, negative regulations and positive regulation (for
			molecular functions). Names, synonyms and definitions are all
			generated automatically</description>
		<ontology name="GeneOntology" />
		<obonamespace>biological_process</obonamespace>
		<fields>
			<field name="target" required="true">
				<prefixes>
					<prefix>regulation</prefix>
					<prefix>negative_regulation</prefix>
					<prefix>positive_regulation</prefix>
				</prefixes>
				<ontology name="GeneOntology">
					<branch>molecular_function</branch>
				</ontology>
			</field>
			<field name="DefX_Ref">
				<cardinality>1..N</cardinality>
			</field>
		</fields>
		<rule> <![CDATA[
function run() {
  var go = GeneOntology;
  var x = termgenie.getSingleTerm("target", go);
  // molecular function
  var check = termgenie.checkGenus(x, "GO:0003674", go);
  if (check.isGenus() !== true) {
    termgenie.error(check.error());
    return;
  }
  if (termgenie.genus(x, "GO:0065007", go)) {
    // biological regulation
    termgenie.error(
      "Cannot create 'regulation of regulation of X' terms. The term "+
      termgenie.getTermShortInfo("GO:0065007", go)+
      " is a parent of "+
      termgenie.getTermShortInfo(x, go)+
      ".");
    return;
  }
  var prefixes = termgenie.getInputs("target");
  if (!prefixes || prefixes === null || prefixes.length === 0) {
    termgenie.error("Could not create a term for X, as no prefix was selected");
    return;
  }
  var count = 0;
  if (termgenie.contains(prefixes, "regulation")) {
    var label = "regulation of "+ termgenie.name(x, go);
    var definition = "Any process that modulates the frequency, rate or extent of "+termgenie.name(x, go)+".";
    var synonyms = termgenie.synonyms("regulation of ", x, go, null, label);
    var cdef = termgenie.cdef("GO:0065007");
    cdef.differentium("regulates", x, go);
    termgenie.createTerm(label, definition, synonyms, cdef);
    count += 1;
  }
  if (termgenie.contains(prefixes, "negative_regulation")) {
    var label = "negative regulation of "+ termgenie.name(x, go);
    var definition = "Any process that stops, prevents or reduces the frequency, rate or extent of "+termgenie.name(x, go)+".";
    var synonyms = termgenie.synonyms("negative regulation of ", x, go, null, label);
    var cdef = termgenie.cdef("GO:0065007");
    cdef.differentium("negatively_regulates", x, go);
    termgenie.createTerm(label, definition, synonyms, cdef);
    count += 1;
  }
  if (termgenie.contains(prefixes, "positive_regulation")) {
    var label = "positive regulation of "+ termgenie.name(x, go);
    var definition = "Any process that activates or increases the frequency, rate or extent of "+termgenie.name(x, go)+".";
    var synonyms = termgenie.synonyms("positive regulation of ", x, go, null, label);
    var cdef = termgenie.cdef("GO:0065007");
    cdef.differentium("positively_regulates", x, go);
    termgenie.createTerm(label, definition, synonyms, cdef);
    count += 1;
  }
  if (count === 0) {
    termgenie.error("Could not create a term for X, as no known prefix was selected");
  }
};]]>
		</rule>
	</template>
	<template name="involved_in">
		<description>processes involved in other processes</description>
		<hint>[part] involved in [whole]</hint>
		<ontology name="GeneOntology" />
		<obonamespace>biological_process</obonamespace>
		<requires>biological_process_xp_self.obo</requires>
		<fields>
			<field name="part" required="true">
				<ontology name="GeneOntology">
					<branch>biological_process</branch>
				</ontology>
			</field>
			<field name="whole" required="true">
				<ontology name="GeneOntology">
					<branch>biological_process</branch>
				</ontology>
			</field>
			<field name="Name" />
			<field name="Definition" />
			<field name="DefX_Ref">
				<cardinality>1..N</cardinality>
			</field>
			<field name="Comment" />
		</fields>
		<rule> <![CDATA[
function run(){
  var go = GeneOntology;
  var p = termgenie.getSingleTerm("part", go);
  var w = termgenie.getSingleTerm("whole", go);
  var check = termgenie.checkGenus(p, "GO:0008150", go);
  if (check.isGenus() !== true) {
    termgenie.error(check.error());
    return;
  }
  var check = termgenie.checkGenus(w, "GO:0008150", go);
  if (check.isGenus() !== true) {
    termgenie.error(check.error());
    return;
  }
  var label = termgenie.name(p, go) + " involved in " + termgenie.name(w, go);
  var definition = "Any "+termgenie.name(p, go)+" that is involved in "+termgenie.name(w, go)+".";
  var synonyms = termgenie.synonyms(null, p, go, " of ", w, go, null, label);
  var cdef = termgenie.cdef(p);
  cdef.differentium("part_of", w, go);
  termgenie.createTerm(label, definition, synonyms, cdef);
};]]>
		</rule>
	</template>
	<template name="occurs_in">
		<description>processes occurring in parts of the cell</description>
		<ontology name="GeneOntology" />
		<obonamespace>biological_process</obonamespace>
		<requires>biological_process_xp_cellular_component.obo</requires>
		<fields>
			<field name="process" required="true">
				<ontology name="GeneOntology">
					<branch>biological_process</branch>
				</ontology>
			</field>
			<field name="location" required="true">
				<ontology name="GeneOntology">
					<branch>cellular_component</branch>
				</ontology>
			</field>
			<field name="Name" />
			<field name="Definition" />
			<field name="DefX_Ref">
				<cardinality>1..N</cardinality>
			</field>
			<field name="Comment" />
		</fields>
		<rule> <![CDATA[
function run() {
  var go = GeneOntology;
  var p = termgenie.getSingleTerm("process", go);
  var c = termgenie.getSingleTerm("location", go);
  var check = termgenie.checkGenus(p, "GO:0008150", go);
  if (check.isGenus() !== true) {
    termgenie.error(check.error());
    return;
  }
  check = termgenie.checkGenus(c, "GO:0005575", go);
  if (check.isGenus() !== true) {
    termgenie.error(check.error());
    return;
  }
  var label = termgenie.name(p, go) + " in " + termgenie.name(c, go);
  var definition = "Any "+termgenie.name(p, go)+" that takes place in "+termgenie.name(c, go)+".";
  var synonyms = termgenie.synonyms(null, p, go, " in ", c, go, null, label);
  var cdef = termgenie.cdef(p);
  cdef.differentium("OBO_REL:occurs_in", c, go);
  termgenie.createTerm(label, definition, synonyms, cdef);
};]]>
		</rule>
	</template>
	<template name="regulation_by">
		<description>processes regulated by other regulating processes
		</description>
